# -*- coding: utf-8 -*-
"""CollocationPhaseo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18kKRsZMBRgI9cPCQPVxkUk6k5KjQ0Z3-
"""

from bs4 import BeautifulSoup
import re

def scan_collocations(html_content):
    soup = BeautifulSoup(html_content, 'html.parser')
    results = []

    #регулярное выражение для поиска
    marker_pattern = re.compile(r'(⸢SYM_COLLOCATION⸣|~)')

    #заранее запишем все абзацы, где есть эти маркеры
    paragraphs = soup.find_all('p')

    for p in paragraphs:
        p_text = p.get_text()
        if not marker_pattern.search(p_text):
            continue

        clean_p_text = re.sub(r'\s+', ' ', p_text).strip()
        parts = re.split(r'(⸢SYM_COLLOCATION⸣|~)', clean_p_text)

        for i in range(1, len(parts), 2):
            marker_type = parts[i]  #сохраним сам маркер
            content = parts[i+1] if (i+1) < len(parts) else ""

            if not content.strip():
                continue

            match = re.search(r'^((?:[^А-ЯЁ]*[А-ЯЁ]){2}[^А-ЯЁ]*)\s+([А-ЯЁ\[].*)', content.strip())

            if match:
                expr_part = match.group(1).strip() #выражение
                quote_part = match.group(2).strip() #цитата с источником

            results.append({
                "marker": marker_type,
                "type": "collocation" if "SYM" in marker_type else "phraseology",
                "expression_and_def": expr_part,
                "quote_and_source": quote_part
            })

    return results

# Пример запуска:

file_path = (r'/content/989_ЗАТВЕРД.html')
with open(file_path, 'r', encoding='utf-8') as f:
    html_file = f.read()

results = scan_collocations(html_file)
for item in results:
  print(f"[{item['type']}] {item['expression_and_def']} - {item['quote_and_source']}")